In [82]:
pd.__version__

'2.2.3'

In [83]:
import numpy as np
import pandas as pd

In [84]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [86]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [87]:
df['fuel_efficiency_mpg'].describe()

count    10000.000000
mean        29.997700
std          2.930245
min         19.800000
25%         28.000000
50%         30.000000
75%         31.900000
max         41.200000
Name: fuel_efficiency_mpg, dtype: float64

In [88]:
df['horsepower'].median()

254.0

In [89]:
df['horsepower'].value_counts()

horsepower
252.0    174
256.0    168
246.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [90]:
df['horsepower'] = df['horsepower'].fillna(252)

In [91]:
df['horsepower'].median()

252.0

In [92]:
df['origin'].unique()

array(['Europe', 'Asia', 'USA'], dtype=object)

In [93]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [94]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values

In [95]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [96]:
XTX = X.T @ X

In [97]:
XTX_inv = np.linalg.inv(XTX)

In [98]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [99]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [100]:
w.sum()

np.float64(0.36919696904925486)